export const ADD_SESSION = "ADD_SESSION";
export const DELETE_SESSION = "DELETE_SESSION";
export const ADD_SESSION_DATA = "ADD_SESSION_DATA";
export const UPDATE_SESSION = "UPDATE_SESSION";
export const CONNECT_WALLET = "CONNECT_WALLET";
export const DISCONNECT_WALLET = "DISCONNECT_WALLET";